---
- name: PostgreSQL DB demo
  hosts: localhost
  become: true
  vars:
    db_name: initdb
    tb_name: mytable
  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Create db
      community.postgresql.postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: true
      become_user: postgres

    - name: Create table
      community.postgresql.postgresql_table:
        state: present
        db: "{{ db_name }}"
        name: "{{ tb_name }}"
        columns:
        - food_id BIGSERIAL PRIMARY KEY
        - food_name VARCHAR(250) NOT NULL
        - calories NUMERIC NOT NULL
        - protein NUMERIC NOT NULL
        - carbohydrates NUMERIC NOT NULL
        - fat NUMERIC NOT NULL
        owner: postgres
      become: true
      become_user: postgres        