---
- name: PostgreSQL 15 Demo
  hosts: all
  become: true
  tasks:
    - name: Install packagess
      ansible.bultin.yum:
        name:
          - postgresql
          - postgresql-server
          - python3-psycog2
        state: present

    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      ansible.builtin.shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Start and enable service
      ansible.bultin.service:
      name: postgresql
      state: started
      enable: true