---
- name: PostgreSQL Granting Privileges
  hosts: localhost
  become: true
  vars:
    db_user: myuser
    db_name: initdb
    tb_name: mytable

  tasks:
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Grant db user access to db
      community.postgresql.postgresql_privs:
        type: database
        database: "{{ db_name }}"
        role: "{{ db_user }}"
        priv: CONNECT
        grant_option: true
      become: true
      become_user: postgres

    - name: Grant db user read access to tb
      community.postgresql.postgresql_privs:
        type: table
        database: "{{ db_name }}"
        objs: "{{ tb_name }}"
        schema: public
        role: "{{ db_user }}"
        priv: SELECT
        grant_option: true
      become: true
      become_user: postgres