---
- name: PostgreSQL User/Role Creation
  hosts: localhost
  become: true
  vars:
    db_user: myuser
    db_password: mypassword
  tasks: 
    - name: Utility present
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    
    - name: Create db user
      community.postgresql.postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: true
      become_user: postgres